# Site settings
title: Breizhcamp
email: team@breizhcamp.org
description: La conférence des développeurs du grand ouest
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.breizhcamp.org/" # the base hostname & protocol for your site
twitter_username: breizhcamp
github_username:  
disqus_shortname: breizhcampblog

# Build settings
markdown: kramdown

# Owner/author information
owner:
  name:           Breizhcamp
  avatar:         avatar.png
  bio:            "La conférence des développeurs du grand ouest"
  email:          team@breizhcamp.org
  # Social networking links used in footer. Update and remove as you like.
  twitter:  breizhcamp
  #facebook:       
  github:         
  #stackexchange:  
  #linkedin:       
  #instagram:      
  #flickr:         
  #tumblr:         
  # google plus id, include the '+', eg +mmistakes
  google_plus:   

# Analytics and webmaster tools stuff goes here
google_analytics:   
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Paris
future:      true
# Amount of posts to show on home page
paginate: 5

exclude: [vendor]