#!/bin/bash

# only proceed script when started not by pull request (PR)
if [ $TRAVIS_PULL_REQUEST == "true" ]; then
  echo "this is PR, exiting"
  exit 0
fi

# enable error reporting to the console
set -e

# build site with jekyll, by default to `_site' folder
bundle install
bundle exec jekyll build


# cleanup
#rm -rf ../gh-pages

#clone `master' branch of the repository using encrypted GH_TOKEN for authentification
git clone --branch=gh-pages https://${GH_TOKEN}@github.com/breizhcamp/blog.git ../gh-pages

# copy generated HTML site to `gh-pages' branch
cp -R _site/* ../gh-pages

# commit and push generated content to `master' branch
# since repository was cloned in write mode with token auth - we can push there
cd ../gh-pages
git config user.email "${GIT_EMAIL}"
git config user.name "${GIT_NAME}"
git add -A .
git commit -a -m "Travis #$TRAVIS_BUILD_NUMBER"
#git push --quiet origin gh-pages > /dev/null 2>&1 
git push origin gh-pages