= Go, Go, Go

Toute l'équipe du BreizhCamp se mobilise en cette rentrée pour vous préparée une édition 2016 à la hauteur de nos engagements.

Tout d'abord, nous vous avions promis de doubler la capacité d'accueil, les places pour 2015 étant toute parties en à peine 6 jour. Challenge relevé, avec un changement de lieu : nous serons accueillis en 2016 dans les locaux de l'Université Rennes 1. Pour nous cela veut dire pas mal d'inconnues à résoudre, mais le jeu en vaut la chandelle.

Ensuite, l'édition 2016 change de période et se déroulera du **23 au 25 mars** - de toute façon en juin il pleut aussi. Ca peut sembler un détail mais pour nous cela veut dire qu'il faut sensiblement avancer notre agenda de préparation pour cette édition et grignoter 3 mois sur le rythme bien établi que la team avait acquis au cours des éditions précédentes.

Bref, nous allons vous faire part de tout ça dans ce nouveau blog, alors **bienvenu à tous sur le blog de la team BreizhCamp** !

:hp-tags: BreizhCamp, blog